apiVersion: v1
kind: Pod
metadata:
 name: k8stest-liveness
spec:
 containers:
 - image: figent/k8stest-unhealthy
   name: moringak8s
   livenessProbe:
     httpGet:
       path: /
       port: 8080
     initialDelaySeconds: 15